[package]
name = "char-count"
version = "0.1.0"
authors = ["vinhbhn"]
description = "A character count service"
edition = "2018"
publish = false

[[bin]]
name = "char_count"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.6.11"

[dev-dependencies]
marine-rs-sdk-test = "0.2.0"
